services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - polyglotnet

  mongo:
    image: mongo:7.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d
    networks:
      - polyglotnet

  neo4j:
    image: neo4j:5.19
    container_name: neo4j_db
    restart: always
    ports:
      - "7474:7474"   # browser
      - "7687:7687"   # bolt driver
    environment:
      NEO4J_AUTH: neo4j/password123
    volumes:
      - ./neo4j:/var/lib/neo4j/import
    networks:
      - polyglotnet

  redis:
    image: redis:7.2
    container_name: redis_db
    restart: always
    ports:
      - "6379:6379"
    networks:
      - polyglotnet

  app:
    container_name: app_service
    build: ./app
    restart: always
    depends_on:
      - mysql
      - mongo
      - neo4j
      - redis
    networks:
      - polyglotnet
    command: tail -f /dev/null



networks:
  polyglotnet:
    driver: bridge
